### ISSUE TITLE
Azure SQL server name has uppercase

### ISSUE THREAD

**Issue by ntabris** [brwilkinson/AzureDeploymentFramework#3]
Turns out that you can create Azure SQL server with name that contains uppercase, but if you have geo-replica and try to failover and the secondary that you're trying to failover to has uppercase in server name, you'll get error and won't be able to failover!

Here's documentation that says server name shouldn't have uppercase: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftsql

Portal prevents you from creating server with uppercase in name, but doesn't throw error if you do deploy server via ARM templates.

Probably here you should convert server name to all lowercase:
https://github.com/brwilkinson/AzureDeploymentFramework/blob/main/ADF/templates-nested/azSQL.json

**Comment by brwilkinson** [comment]
Hey @ntabris thanks for the info 👍

I moved the ARM json to a new branch over the weekend. Then in dev/main branches I archived the ARM/Json files off. I wasn't planning to delete them straight away, however I can bring them back and maintain them if you like?

I was thinking of just using Bicep templates moving forward.

Either way I'll make is update.

**Comment by ntabris** [comment]
I have no objection to you archiving the ARM files; the ARM docs (plus some occasional trial and error) are adequate for me to figure things out, though I do appreciate having your ARM files still available as a reference, so an archive branch for them sounds good!

**Comment by brwilkinson** [comment]
I will leave it over here for now: https://github.com/brwilkinson/AzureDeploymentFramework/tree/armjson/ADF

All new and migrated templates are in a single directory now for Bicep
https://github.com/brwilkinson/AzureDeploymentFramework/tree/main/ADF/bicep

They are plug and play against the old templates ... except you just need to tweak the deployment scripts a little to deploy .bicep instead of .json extensions other than that they use the exact same inputs and parameter files Etc.

Also you don't need to stage/upload the bicep files to storage, only the DSC/Script extension files.

Anyway it took me a few months to migrate all of my JSON to Bicep, so I doubt that would be a project that would be too exciting for a production migration, given the amount of templates that you have. I mean it's Type 2 fun.

You could just swap out your Deploy ALL scripts to Bicep... since bicep can deploy both JSON and ARM. That way you can migrate some to Bicep (or over time) and add new templates as Bicep. That would be fairly straight forward.

My Bicep deploy all are here: 
https://github.com/brwilkinson/AzureDeploymentFramework/blob/main/ADF/bicep/00-ALL-SUB.bicep
https://github.com/brwilkinson/AzureDeploymentFramework/blob/main/ADF/bicep/01-ALL-RG.bicep

The nested deployments on those, which are modules can point to JSON templates or Bicep templates.
